[package]
name = "immuno_genotyper"
version = "0.0.1"
authors = ["Sebastian Benjamin <sebastiancbenjamin@gmail.com>"]
edition = "2018"

[dependencies]
bio = "0.31.0"
clap = { version = "2.33.1", features = ["yaml"] }
rayon = "1.3.1"
csv = "1.1.3"
num_cpus = "1.13.0"
debruijn = { git = "https://github.com/10XGenomics/rust-debruijn" }
debruijn_mapping = { git = "https://github.com/10XGenomics/rust-pseudoaligner", rev = "8533e36a8c7c70de23b57b088d382139fd4d6a2c" }