[package]
name = "immuno_genotyper"
version = "0.0.1"
authors = ["Sebastian Benjamin <sebastiancbenjamin@gmail.com>"]
edition = "2018"

[dependencies]
bio = "0.31.0"
clap = { version = "2.33.1", features = ["yaml"] }
csv = "1.1.3"
rust-htslib = "0.32.0"
debruijn = { git = "https://github.com/10XGenomics/rust-debruijn" }
debruijn_mapping = { git = "https://github.com/devsebb/rust-pseudoaligner", branch = "pseudoaligner/configure-mismatch" }