[package]
name = "immuno_genotyper"
version = "0.0.1"
authors = ["Sebastian Benjamin <sebastiancbenjamin@gmail.com>"]
edition = "2018"

[dependencies]
bio = "0.31.0"
num_cpus = "1.13.0"
rayon = "1.3.1"
csv = "1.1.3"