name: Release on push to main
on:
  push:
    branches:
      - 'main'

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create release
        id: create_release
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Release
      - shell: bash
        run: |
          cut -d " " -f1 <<<'${{ steps.create_release.outputs.upload_url }}' > url.txt
      - name: Save release URL
        uses: actions/upload-artifact@v2
        with:
          name: url
          path: url.txt

  build:
    needs: release
    name: Build and upload release asset
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: Linux.out
            asset_name: Linux.out
            asset_path: ./target/x86_64-unknown-linux-musl/release/
          - os: macos-latest
            artifact_name: MacOS.out
            asset_name: MacOS.out
            asset_path: ./target/release/
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - shell: bash
        if: ${{matrix.os == 'ubuntu-latest'}}
        run: |
          sudo apt install musl-tools
      - shell: bash
        if: ${{matrix.os == 'ubuntu-latest'}}
        run: |
          rustup target add x86_64-unknown-linux-musl
      - name: Ubuntu Build
        if: ${{matrix.os == 'ubuntu-latest'}}
        run: cargo build --release --target x86_64-unknown-linux-musl
      - name: MacOS Build
        if: ${{matrix.os == 'macos-latest'}}
        run: cargo build --release
      - shell: bash
        run: |
          mv ${{ matrix.asset_path }}nimble ${{ matrix.asset_path }}${{ matrix.artifact_name }}
      - name: Download release url
        uses: actions/download-artifact@v2
        with:
          name: url
      - name: Read release URL
        id: url
        uses: pCYSl5EDgo/cat@master
        with:
          path: url.txt
      - name: Upload binary to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.url.outputs.text }}
          asset_path: ${{ matrix.asset_path }}${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          asset_content_type: application/octet-stream
