name: Release on push to main

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    name: Build and upload release assets
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact_name: Linux.out
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: MacOS.out
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: Windows.exe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install musl-tools

      - name: Add Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename artifact
        shell: bash
        run: mv target/${{ matrix.target }}/release/nimble target/${{ matrix.target }}/release/${{ matrix.artifact_name }}

      - name: Generate release tag
        id: tag
        run: echo "release_tag=release_$(date +"%Y.%m.%d_%H-%M")" >> $GITHUB_ENV

      - name: Upload binary to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.release_tag }}
          files: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
